### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException when md files are scanned

### ISSUE THREAD

**Issue by nishwalshetty** [Trivadis/plsql-cop-sonar#9] opened 2023-05-15 08:44 UTC
version - sonarqube 9.9 lts
plsql-cop version - sonar-plsql-cop-standalone-8.9.6

error as below

INFO: Sensor PlSQL COP Sensor [plsqlcop]
INFO: Process resource README.md
INFO: Process resource README.md
INFO: Process resource README.md
INFO: Process resource README.md
INFO: Process resource readme.md
INFO: Process resource README.md
INFO: Process resource readme.md
INFO: Process resource readme.md
INFO: Process resource readme.md
INFO: Process resource readme.md
INFO: Process resource README.md
INFO: Process resource readme.md
INFO: Process resource README.md
INFO: Process resource README.md
INFO: Process resource readme.md
INFO: Process resource readme.md
INFO: Process resource readme.md
INFO: Process resource readme.md
INFO: Process resource readme.md
INFO: Process resource readme.md
INFO: Process resource readme.md
INFO: Process resource readme.md
INFO: Process resource readme.md
INFO: Process resource readme.md
INFO: Process resource spec-vs-feature-v0.1.0.md
INFO: Process resource README.md
INFO: Process resource README.md
INFO: Process resource readme.md
INFO: Process resource readme.md
INFO: Process resource readme.md
INFO: Process resource readme.md
INFO: Process resource readme.md
INFO: Process resource README.md
INFO: Process resource README.md
INFO: Process resource README.md
INFO: Process resource readme.md
INFO: Process resource readme.md
INFO: Process resource readme.md
INFO: Process resource readme.md
INFO: Process resource readme.md
INFO: Process resource readme.md
INFO: Process resource readme.md
INFO: Process resource README.md
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 2:43:22.561s
INFO: Final Memory: 36M/130M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarScanner execution
java.lang.StringIndexOutOfBoundsException: index 0,length 0
	at java.base/java.lang.String.checkIndex(Unknown Source)
	at java.base/java.lang.AbstractStringBuilder.charAt(Unknown Source)
	at java.base/java.lang.StringBuilder.charAt(Unknown Source)
	at com.trivadis.oracle.sqlplus.SqlPlusResource.isMarkdown(SqlPlusResource.java:77)
	at com.trivadis.oracle.sqlplus.SqlPlusResource.doLoad(SqlPlusResource.java:123)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1563)
	at com.trivadis.tvdcc.process.ResourceHandler$2.load(ResourceHandler.java:40)
	at com.trivadis.tvdcc.process.ResourceValidatorImpl.performValidation(ResourceValidatorImpl.java:49)
	at com.trivadis.tvdcc.process.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:40)
	at com.trivadis.tvdcc.process.ValidationTask.analyze(ValidationTask.java:146)
	at com.trivadis.tvdcc.process.ValidationTask.process(ValidationTask.java:108)
	at com.trivadis.sonar.plugin.AbstractPlSqlCopSensor.analyzeInputFile(AbstractPlSqlCopSensor.java:101)
	at com.trivadis.sonar.plugin.AbstractPlSqlCopSensor.analyze(AbstractPlSqlCopSensor.java:88)
	at com.trivadis.sonar.plugin.AbstractPlSqlCopSensor.execute(AbstractPlSqlCopSensor.java:53)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:64)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:88)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:61)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:79)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:61)
	at org.sonar.scanner.scan.SpringModuleScanContainer.doAfterStart(SpringModuleScanContainer.java:82)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.scanner.scan.SpringProjectScanContainer.scan(SpringProjectScanContainer.java:403)
	at org.sonar.scanner.scan.SpringProjectScanContainer.scanRecursively(SpringProjectScanContainer.java:399)
	at org.sonar.scanner.scan.SpringProjectScanContainer.doAfterStart(SpringProjectScanContainer.java:368)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.scanner.bootstrap.SpringGlobalContainer.doAfterStart(SpringGlobalContainer.java:137)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)

Note: for now exclduing md files from global settings work, but i believe by default md files should be excluded or this needs to be handled better

**Comment by PhilippSalvisberg** [comment] 2023-05-15 11:47
Thanks for reporting this issue. Markdown files (and any other files) should not cause such an abortion. I cannot reproduce the error on my side with the Markdown files I used. Could you please provide a Markdown file that causes this error? Thank you.

**Comment by PhilippSalvisberg** [comment] 2023-10-03 06:58
Fixed with version 8.9.7

**Closed as completed by PhilippSalvisberg** 2023-10-03 06:58 UTC
Labels: bug
